# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tocr.proto\x12\x03ocr\"3\n\nOCRRequest\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\x12\x11\n\tfile_type\x18\x02 \x01(\t\"\x1b\n\x0bOCRResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"-\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"3\n\x0f\x41nalyzeResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08raw_text\x18\x02 \x01(\t2x\n\nOCRService\x12\x30\n\x0b\x45xtractText\x12\x0f.ocr.OCRRequest\x1a\x10.ocr.OCRResponse\x12\x38\n\x0b\x41nalyzeText\x12\x13.ocr.AnalyzeRequest\x1a\x14.ocr.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=18
  _globals['_OCRREQUEST']._serialized_end=69
  _globals['_OCRRESPONSE']._serialized_start=71
  _globals['_OCRRESPONSE']._serialized_end=98
  _globals['_ANALYZEREQUEST']._serialized_start=100
  _globals['_ANALYZEREQUEST']._serialized_end=145
  _globals['_ANALYZERESPONSE']._serialized_start=147
  _globals['_ANALYZERESPONSE']._serialized_end=198
  _globals['_OCRSERVICE']._serialized_start=200
  _globals['_OCRSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
